### ISSUE TITLE
Steering behaviours

### ISSUE THREAD

**Issue by kyle-robinson** [Nine-Byte-Warriors/five-nights-of-farming#14]
Create a range of steering behaviours to support varying enemy movement patterns.

**Comment by BlackRece** [comment]
Flee, Seek, Idle behaviours have been completed.
Currently working on patrol.
Future behaviours include; separation, wander, obstacle avoid, follow, cohesion and alignment.

**Comment by kyle-robinson** [comment]
Prioritize: Wander, follow, patrol.
Consider: Separation, cohesion, alignment
Ignore (for now): Obstacle avoidance
