### ISSUE TITLE
Audio file playing/stopping

### ISSUE THREAD

**Issue by kyle-robinson** [Nine-Byte-Warriors/five-nights-of-farming#26]
Extend the functionality of the audio engine to allow for audio files to be played and stopped. This should account for multiple audio files playing at the same time.

**Comment by juliusz-kaczmarek** [comment]
What's done it

- Playing one shot sound, these cannot be stopped, they are too short anyway
- Playing music, these can be stopped and paused (to test it properly, I need to create an audio editor first though)
