### ISSUE TITLE
UI system

### ISSUE THREAD

**Issue by kyle-robinson** [Nine-Byte-Warriors/five-nights-of-farming#7]
Create a system that allows for UI elements to be added.
These should not interact with the game sprites and should always be drawn on top of everything else.

**Comment by juliusz-kaczmarek** [comment]
Seems cool, although 2 issues:
- If you keep the left mouse button clicked, anything you hover is interacting with it (e.g. you drag through github button it will open the website despite not clicking on it specifically). **This should be fixed before first pass in my opinion.**
- The scroll drag is changing it's position to the top of the scroll drag sprite, regardless where you clicked on it. **This can wait, but should be fixed later.**
